export const INPUTS_ID = [
	"hotels-number",
	"hotel-type",
	"rooms-number",
	"occupancy",
	"adr",
	"rms-implemented",
	"rms-rooms-system",
	"rms-restaurant-system",
	"rms-fb-system",
	"average-stay",
	"guest-messaging",
	"average-guest-stay",
	"pre-stay",
	"in-tay",
	"revenue-retention",
];
