export const GROUPS = {
  metaverse: [
    'segmentation',
    'competitor-pricing',
    'event-data',
    'laundry',
    'attribute-based-pricing',
    'index-rates',
  ],
  experiences: [
    'tour-operation',
    'channel-differentiated-pricing',
    'wholesalers',
    'ota',
    'corporate',
  ],
  'post-booking': [
    'crew',
    'energy-sources',
    'measure-time-time',
    'rate-parity',
    'loyalty-programme',
    'added-direct-channels',
  ],
  'check-in': [
    'direct-channels',
    'inventory-parity',
    'price-rooms-individually',
    'yieldable',
    'leisure',
    'buying',
  ],
  'post-check-in': [
    'mice',
    'cleaning-room',
    'water-recycling',
    'energy-panels',
    'sell-packages',
    'market-positioning',
    'upgrades-dynamic-pricing',
  ],
  'check-out': [
    'cor',
    'market-data',
    'flight-data',
    'dynamic-pricing',
    'policy-price',
    'resource-retention',
  ],
  'experiences-outside': [
    'quality-data-point',
    'purchase',
    'plastic-amenities',
    'price-groups',
    'sustainability',
  ],
};
