import colors from '@root/colors.json';
import { ChartData } from 'components/Chart/Bubble';

export const bubbles: { [key: string]: Omit<ChartData, 'id'> } = {
  pms: {
    r: 2,
    color: colors.blue,
    label: 'PMS',
    visible: false,
    fill: false,
    y: 36,
    x: -28,
  },
  crm: {
    r: 2.4,
    color: colors.violet,
    label: 'CRM',
    visible: false,
    fill: false,
    y: 27,
    x: -23,
  },
  c: {
    r: 2.3,
    color: colors.violet,
    label: 'PRICING',
    visible: false,
    fill: false,
    y: 29,
    x: -42,
  },
  d: {
    r: 3,
    color: colors.violet,
    label: 'BRAND.COM',
    visible: false,
    fill: false,
    y: 13,
    x: -35,
  },
  e: {
    r: 2,
    color: colors.blue,
    label: 'META SEARCH',
    visible: false,
    fill: false,
    y: 15,
    x: -46,
  },
  'channel-manager': {
    r: 3,
    color: colors.blue,
    label: 'CHANNEL MANAGER',
    visible: false,
    fill: false,
    y: 30,
    x: -35,
  },
  loyalty: {
    r: 3.4,
    color: colors.orange,
    label: 'LOYALTY',
    visible: false,
    fill: false,
    y: 22,
    x: -29,
  },
  h: {
    r: 3,
    color: colors.blue,
    label: 'MESSAGING CONFIRMATION',
    visible: false,
    fill: false,
    y: 10,
    x: -22,
  },
  i: {
    r: 2,
    color: colors.orange,
    label: 'QR CODES',
    visible: false,
    fill: false,
    y: 26,
    x: -18,
  },
  j: {
    r: 2,
    color: colors.orange,
    label: "OTA'S",
    visible: false,
    fill: false,
    y: -2,
    x: -41,
  },
  k: {
    r: 4.2,
    color: colors.orange,
    label: 'UP-SELLING UNIQUE GUEST PORTAL',
    visible: false,
    fill: false,
    y: 20,
    x: -2,
  },
  'chat-bot': {
    r: 2,
    color: colors.orange,
    label: 'CHAT BOTS',
    visible: false,
    fill: false,
    y: -7,
    x: -32,
  },
  m: {
    r: 3,
    color: colors.orange,
    label: 'GOOGLE',
    visible: false,
    fill: false,
    y: -20,
    x: -43,
  },
  'bi-big-data': {
    r: 2,
    color: colors.violet,
    label: 'BIG DATA',
    visible: false,
    fill: false,
    y: -10,
    x: -45,
  },
  gds: {
    r: 3,
    color: colors.blue,
    label: 'GDS',
    visible: false,
    fill: false,
    y: -13,
    x: -37,
  },
  p: {
    r: 3,
    color: colors.violet,
    label: 'LIVECHAT',
    visible: false,
    fill: false,
    y: -30,
    x: -35,
  },
  'e-concierge': {
    r: 3.2,
    color: colors.blue,
    label: 'E-CONCIERGE',
    visible: false,
    fill: false,
    y: -23,
    x: -25,
  },
  r: {
    r: 3.2,
    color: colors.blue,
    label: 'ONLINE REP MANAGEMENT',
    visible: false,
    fill: false,
    y: -4,
    x: -17,
  },
  s: {
    r: 2,
    color: colors.orange,
    label: 'CRS',
    visible: false,
    fill: false,
    y: 45,
    x: -35,
  },
  t: {
    r: 2,
    color: colors.violet,
    label: 'SURVEYS',
    visible: false,
    fill: false,
    y: -20,
    x: -7,
  },
  u: {
    r: 2,
    color: colors.blue,
    label: 'HOUSE KEEPING',
    visible: false,
    fill: false,
    y: -3,
    x: -4,
  },
  v: {
    r: 2.4,
    color: colors.blue,
    label: 'GDPR & DPA',
    visible: false,
    fill: false,
    y: 40,
    x: 18,
  },
  w: {
    r: 4.2,
    color: colors.blue,
    label: 'AUTOMATION AND SCALING THE GUEST JOURNEY',
    visible: false,
    fill: false,
    y: 20,
    x: 13,
  },
  x: {
    r: 4.3,
    color: colors.blue,
    label: 'SEGMENTATION OF OFFERS AND COMMUNICATION',
    visible: false,
    fill: false,
    y: 27,
    x: 25,
  },
  y: {
    r: 3,
    color: colors.blue,
    label: 'SPEAKING THE GUEST LANGUAGE',
    visible: false,
    fill: false,
    y: 35,
    x: 37,
  },
  z: {
    r: 4.5,
    color: colors.blue,
    label: 'PERSONALISATION',
    visible: false,
    fill: false,
    y: 2,
    x: 40,
  },
  a1: {
    r: 2,
    color: colors.violet,
    label: 'KEYS',
    visible: false,
    fill: false,
    y: -25,
    x: 30,
  },
  b2: {
    r: 3,
    color: colors.blue,
    label: 'CHECK IN SOLUTIONS',
    visible: false,
    fill: false,
    y: -30,
    x: 15,
  },
};
